#!/usr/bin/env bash
# script that will display information about subdomains

domain_info () {
    local line
    line=$(dig "$2"."$1" +short)

    if [ -n "$line" ]; then
        echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    else
        echo "No information found for subdomain $2"
    fi
}

if [ "$#" -eq 1 ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        domain_info "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    domain_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
