#!/bin/bash

# Update package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Start Nginx (without using systemctl)
sudo /etc/init.d/nginx start

# Create a custom HTML file with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Check Nginx configuration and reload
sudo nginx -t
sudo /etc/init.d/nginx reload
