#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start
