#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a configuration file for the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/3-redirection <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Add other server configurations as needed
}
EOF'

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/3-redirection /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart
