#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Configure Nginx to include the custom header
echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo systemctl restart nginx

# Exit with success
exit 0
