#!/usr/bin/env bash
# use for and case
counter=1
while [ $counter -le 20 ]
do
case $counter in
5)
echo "bad luck from China"
echo $counter
;;
10)
echo "bad luck from Japan"
echo $counter
;;
18)
echo "bad luck from Italy"
echo $counter
;;
*)
echo $counter
;;
esac
((counter++))
done
