#!/usr/bin/env bash
# display directory content
for file in *; do
    if [[ $file != .* ]]; then
        part_after_dash=$(echo "$file" | awk -F'-' '{print $2}')
        echo "$part_after_dash"
    fi
done
